############################################################
# [1] 프로파일 환경별 그룹화
############################################################
spring:
  profiles:
    group:
      dev: common, dev
      local: common, local
    active:
      - dev
---

############################################################
# [2] 공통 환경 설정
############################################################
spring:
  config:
    activate:
      on-profile: common
  application:
    name: puttly-v1
  main:
    # 스프링부트 런타임시 출력되는 콘솔 배너 비활성화
    banner-mode: OFF
  # 타임리프 설정 : 웹 브라우저의 새로고침을 통한 화면단 변경 이력의 반영을 위해 템플릿 경로 및 캐시값 변경
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    # 개발 완료시 활성화 변경
    cache: false
  # 정적 리소스 설정
  web:
    resources:
      # 웹 브라우저 새로고침을 통한 화면단 변경 이력의 반영을 위한 정적 리소스 경로 변경
      static-locations: file:src/main/resources/static/
      cache:
        # 캐싱 기간 지정 : 36000분(10시간)
        period: 36000

# 서버 설정 
server:
  # HTTP 요청 및 응답의 인코딩 설정
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---

############################################################
# [2] 개발(인메모리 DB) 환경 설정
############################################################
spring:
  config:
    activate:
      on-profile: dev
  # H2 인메모리 DB 연결 정보 설정
  datasource:
    url: jdbc:h2:mem:puttly_dev;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  # 스키마 버전 관리 비활성화
  flyway:
    enabled: false
  sql:
    init:
      # DB 초기화 모드 설정 : 내장 데이터베이스 사용 시 스크립트 실행
      mode: EMBEDDED
      schema-locations:
        - classpath:db/schema.sql
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    root: info
    web: debug

server:
  port: 80

---

############################################################
# [3] 로컬 DB 환경 설정
############################################################
spring:
  config:
    activate:
      on-profile: local
  # 로컬 데이터베이스(MariaDB) 연결 정보 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/puttly?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin926
    password: tq5033
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    root: info
    web: info

server:
  port: 81