##################################################
# 스프링 프로파일 그룹화
##################################################
spring:
  profiles:
    group:
      dev: common, dev
      local: common, local
    active:
      - dev